[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.duckdb"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Accept-Ranges = "bytes"

[[headers]]
  for = "/geodata/*.geojson"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Accept-Ranges = "bytes"

