[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.duckdb"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Accept-Ranges = "bytes"

[[redirects]]
  from = "/tiles/*"
  to = "https://tile.openstreetmap.org/:splat"
  status = 200
  force = true
